---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2024/4/25 20:38
---

--1.参数列表
--1.1优惠券的id
local voucherId=ARGV[1]
--1.2用户id
local userId=ARGV[2]
--1.3订单id
local orderId=ARGV[3]

--2.数据key
--2.1库存key
local stockKey='seckill:stock:' .. voucherId
--2.2订单key
local orderKey='seckill:order:' .. voucherId

--3.脚本业务
--3.1判断库存是否充足
if(tonumber(redis.call('get',stockKey))<=0) then
    --库存量不足，返回1
    return 1
end
--3.2判断用户是否已经下单
if(redis.call('sismember',orderKey,userId)==1) then
    --存在，说明重复下单
    return 2
end
--3.3减去库存
redis.call('incrby',stockKey,-1)
--3.4将用户加入到订单的set集合中
redis.call('sadd',orderKey,userId)
--3.5将用户的订单信息加入消息队列 XADD stream.orders * key1 v1 k2 v2
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0



